# Change these first
owner: SystemInternal # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: System.com
    url: https://www.system.com
  - name: GET Topic Graph
    url: $GET_TOPIC_GRAPH
    maxResponseTime: 1000
    headers:
      - "x-api-key: $X_API_KEY"
  - name: GET Studies
    url: $GET_STUDIES
    maxResponseTime: 500
    headers:
      - "x-api-key: $X_API_KEY"
  - name: GET Features
    url: $GET_FEATURES
    maxResponseTime: 500
    headers:
      - "x-api-key: $X_API_KEY"
  - name: GET Models
    url: $GET_MODELS
    maxResponseTime: 500
    headers:
      - "x-api-key: $X_API_KEY"
  - name: GET Datasets
    url: $GET_DATASETS
    maxResponseTime: 500
    headers:
      - "x-api-key: $X_API_KEY"
  - name: GET Topics
    url: $GET_TOPICS
    maxResponseTime: 500
    headers:
      - "x-api-key: $X_API_KEY"
  - name: GET Metrics
    url: $GET_METRICS
    maxResponseTime: 500
    headers:
      - "x-api-key: $X_API_KEY"

assignees:
  - jamessystem

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.8com/SystemInternal/uptime/master/assets/logo.png
  name: System
  introTitle: "**System**'s real-time status dashboard."
  introMessage: System is a free, open, and living public resource that aims to explain how anything in the world is related to everything else. 
  navbar:
    - title: System.com
      href: https://www.system.com
    - title: Dashboard
      href: /uptime/
    - title: Github
      href: https://github.com/SystemInternal/uptime/
    

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
